
[project]
name = "pdf"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["PyMuPDF", "Pillow", "fastapi", "uvicorn", "python-multipart"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
include = ["main.py"]
